// Code generated by protoc-gen-go.
// source: connproto.proto
// DO NOT EDIT!

package connproto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ConnProto_ProType int32

const (
	ConnProto_CALL  ConnProto_ProType = 1
	ConnProto_ACK   ConnProto_ProType = 2
	ConnProto_HEART ConnProto_ProType = 3
)

var ConnProto_ProType_name = map[int32]string{
	1: "CALL",
	2: "ACK",
	3: "HEART",
}
var ConnProto_ProType_value = map[string]int32{
	"CALL":  1,
	"ACK":   2,
	"HEART": 3,
}

func (x ConnProto_ProType) Enum() *ConnProto_ProType {
	p := new(ConnProto_ProType)
	*p = x
	return p
}
func (x ConnProto_ProType) String() string {
	return proto.EnumName(ConnProto_ProType_name, int32(x))
}
func (x ConnProto_ProType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ConnProto_ProType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ConnProto_ProType_value, data, "ConnProto_ProType")
	if err != nil {
		return err
	}
	*x = ConnProto_ProType(value)
	return nil
}

type ConnProto struct {
	Type             *ConnProto_ProType `protobuf:"varint,1,req,enum=connproto.ConnProto_ProType" json:"Type,omitempty"`
	Msgid            *uint64            `protobuf:"fixed64,2,opt" json:"Msgid,omitempty"`
	Ackmsgid         *uint64            `protobuf:"fixed64,3,opt" json:"Ackmsgid,omitempty"`
	Busstype         *int32             `protobuf:"varint,100,opt" json:"Busstype,omitempty"`
	Bussdata         []byte             `protobuf:"bytes,101,opt" json:"Bussdata,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ConnProto) Reset()         { *m = ConnProto{} }
func (m *ConnProto) String() string { return proto.CompactTextString(m) }
func (*ConnProto) ProtoMessage()    {}

func (m *ConnProto) GetType() ConnProto_ProType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ConnProto) GetMsgid() uint64 {
	if m != nil && m.Msgid != nil {
		return *m.Msgid
	}
	return 0
}

func (m *ConnProto) GetAckmsgid() uint64 {
	if m != nil && m.Ackmsgid != nil {
		return *m.Ackmsgid
	}
	return 0
}

func (m *ConnProto) GetBusstype() int32 {
	if m != nil && m.Busstype != nil {
		return *m.Busstype
	}
	return 0
}

func (m *ConnProto) GetBussdata() []byte {
	if m != nil {
		return m.Bussdata
	}
	return nil
}

func init() {
	proto.RegisterEnum("connproto.ConnProto_ProType", ConnProto_ProType_name, ConnProto_ProType_value)
}
